<?php

namespace app\controllers;

use Yii;
use yii\web\Controller;

class DocController extends Controller
{

    private $_defaultController;
    public $postHost;


    public function init()
    {
        $this->_defaultController = new AppController('','');
        $this->postHost = Yii::$app->params["postHost"];
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * 接口文档Method
     * @return string
     */
    public function actionIndex(){

        $ip=$_SERVER["REMOTE_ADDR"];
        if(!($ip=='112.64.233.130'||strpos($ip,'192.168')===0||$ip=='127.0.0.1'||$ip=='::1'||$ip=='localhost')){
            header("Status: 404 Not Found");
            exit();
        }
        $homeUrl="/";
        if(YII_DEBUG)
            $homeUrl=Yii::$app->homeUrl;
        if(!Yii::$app->request->isAjax){
            $defaultDoc=$this -> getDocumentInfo('AppController',"actionIndex");
            $defaultUrl= $this->postHost."/app/index";

            $apiList=array(
                "App"=>"默认接口（App）",
            );
            $defaultMethod=$this->_defaultController->apiNameList;
            return $this->render("index",["postHost"=>$this->postHost,"apiList"=>$apiList,"defaultUrl"=>$defaultUrl,"defaultDoc"=>$defaultDoc,"defaultMethod"=>$defaultMethod]);
        }else{
            $type=Yii::$app->request->post("type");
            $controller=Yii::$app->request->post("controller")."Controller";
            //controller change
            if($type=="mothed"){
                $method='action'.Yii::$app->request->post("method");
                $url= $this->postHost."/".strtolower(Yii::$app->request->post("controller"))."/".Yii::$app->request->post("method");
                $doc=$this -> getDocumentInfo($controller,$method);
                $doc = str_replace("\n", "<br/>", $doc);
                $params=array();
                preg_match_all("/[a-z]*\\$([a-z]|[A-Z])*\b/",$doc,$params);
                exit(json_encode(array("url"=>$url,"doc"=>$doc,"parameter"=>$params[0])));
            }elseif($type=="controller"){
                //get api list
                $methodList=$this->_getApiNameList($controller);
                $defaultMethod=$methodList[0];
                $defaultUrl= $this->postHost."/".strtolower(Yii::$app->request->post("controller"))."/".strtolower($defaultMethod);
                $defaultDoc=$this -> getDocumentInfo($controller,"action".$defaultMethod);
                $defaultDoc = str_replace("\n", "<br/>", $defaultDoc);
                $params=array();
                preg_match_all("/[a-z]*\\$([a-z]|[A-Z])*\b/",$defaultDoc,$params);
                exit(json_encode(array("defaultUrl"=>$defaultUrl,"defaultDoc"=>$defaultDoc,"methodList"=>$methodList,"parameter"=>$params[0])));
            }
        }
    }


    /**
     * 获取方法解释说明
     * @param string $module
     * @param string $fc
     * @return string 返回方法解释说明
     */
    private function getDocumentInfo($module,$fc){
        $func  = new \ReflectionMethod(__NAMESPACE__.'\\'.$module,$fc);
        $tmp   = $func->getDocComment();
        return $tmp;
    }

    /**
     * 获取方法解释说明
     * @param string $module
     * @param string $fc
     * @return string 返回方法解释说明
     */
    private function _getApiNameList($controller){
        $class=null;
        switch($controller){
            case "MsgController":$class=new MsgController("","");break;
            case "AppController":$class=new AppController("","");break;
            case "EmailController":$class=new EmailController("","");break;
            case "DocController":$class=new DocController("","");break;
            case "EappController":$class=new EappController("","");break;
        }
        return $class->apiNameList;
        /*
        if(class_exists($controller)) {//判断类是否存在
            $class = new $controller("", "");
            return $class->apiNameList;
        }
        */
    }

    public function actionError()
    {
        if($error=Yii::$app->errorHandler->exception)
        {
            if(Yii::$app->request->isAjax) {
                echo Yii::$app->errorHandler->convertExceptionToString($error);
            }elseif($error->statusCode=='404') {
                return $this->render("404", ['error' => Yii::$app->errorHandler->convertExceptionToString($error)]);
            }else {
                return $this->render('error', ['code' => $error->statusCode, 'error' => Yii::$app->errorHandler->convertExceptionToString($error)]);
            }
        }
    }

}
